// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
///   import 'firebase_options.dart';
/// // ...
///  await Firebase.initializeApp(
///    options: DefaultFirebaseOptions.currentPlatform,
///  );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ-vSSMFbEZnNwKwRG-hL107OvwH6PmRg',
    appId: '1:131484116902:web:b68e24fa7f48c37ea39167',
    messagingSenderId: '131484116902',
    projectId: 'fluttertoko',
    authDomain: 'fluttertoko.firebaseapp.com',
    storageBucket: 'fluttertoko.appspot.com',
    measurementId: 'G-N7987WLGLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqDMErcB9K0LCiZE_V9sXbROAeowd5QsI',
    appId: '1:131484116902:android:54d15fbfeec2eafca39167',
    messagingSenderId: '131484116902',
    projectId: 'fluttertoko',
    storageBucket: 'fluttertoko.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6mbIWsBFWZYYx2UGUkOFiNvv29fgOJHM',
    appId: '1:131484116902:ios:67352461dcf598f5a39167',
    messagingSenderId: '131484116902',
    projectId: 'fluttertoko',
    storageBucket: 'fluttertoko.appspot.com',
    iosBundleId: 'com.irfan.tokoPaerbe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6mbIWsBFWZYYx2UGUkOFiNvv29fgOJHM',
    appId: '1:131484116902:ios:b7a298cb7782026ea39167',
    messagingSenderId: '131484116902',
    projectId: 'fluttertoko',
    storageBucket: 'fluttertoko.appspot.com',
    iosBundleId: 'com.irfan.tokoPaerbe.RunnerTests',
  );
}
